//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magazalar()
        {
            this.Personeller = new HashSet<Personeller>();
        }
    
        public int MagazaID { get; set; }
        public string MagazaAdi { get; set; }
        public Nullable<int> MagazaTurleriID { get; set; }
        public Nullable<int> AdresID { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual MagazaTurleri MagazaTurleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personeller> Personeller { get; set; }
    }
}
