//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int SiparisID { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
        public int SevkiyatTarihi { get; set; }
        public string Onay { get; set; }
        public Nullable<int> AdresID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<int> NakliyeciID { get; set; }
        public int SepetID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual Nakliyeciler Nakliyeciler { get; set; }
        public virtual Personeller Personeller { get; set; }
        public virtual Sepet Sepet { get; set; }
        public virtual Kullanıcı Kullanıcı { get; set; }
    }
}
